#
# Compile the sass to css and minify it on every commit.
#

language: nodejs
node_js:
  - "4.1"
branches:
  only:
    - master
before_install: gem install sass
before_script:
  - npm install -g grunt-cli
  - npm install
script: grunt dist
